"""Deterministic Ars Magica mechanics helpers."""

from .advancement import (
    XpState,
    adventure_source_quality,
    advancement_total,
    apply_experience,
    exposure_source_quality,
    practice_source_quality,
    score_from_xp,
    teaching_source_quality,
    training_source_quality,
    validate_adventure_allocations,
    validate_single_xp_source,
    xp_to_buy_score,
    xp_to_raise_next,
)
from .audit import AuditResult, Component, ValidationResult
from .casting import (
    CastingOutcome,
    PenetrationOutcome,
    casting_score,
    effective_art_score,
    formulaic_casting_total,
    penetration_bonus,
    penetration_total,
    ritual_casting_total,
    spontaneous_casting_total,
)
from .dice import DieRollResult, RollTraceEntry, apply_die_to_modifier, simple_die, stress_die
from .laboratory import (
    charged_item_charges,
    instilled_effect_vis_cost,
    lab_total,
    laboratory_setup_penalty,
    longevity_ritual,
    seasonal_lab_progress,
    vis_extraction,
    vis_limit,
)
from .spells import (
    RequisiteDecision,
    adjust_spell_level,
    construct_spell_level,
    spell_magnitude,
    validate_spell_constraints,
)
from .validation import validate_non_negative_scores, validate_spell

__all__ = [
    "AuditResult",
    "CastingOutcome",
    "Component",
    "DieRollResult",
    "PenetrationOutcome",
    "RequisiteDecision",
    "RollTraceEntry",
    "ValidationResult",
    "XpState",
    "adjust_spell_level",
    "adventure_source_quality",
    "advancement_total",
    "apply_die_to_modifier",
    "apply_experience",
    "casting_score",
    "charged_item_charges",
    "construct_spell_level",
    "effective_art_score",
    "exposure_source_quality",
    "formulaic_casting_total",
    "instilled_effect_vis_cost",
    "lab_total",
    "laboratory_setup_penalty",
    "longevity_ritual",
    "penetration_bonus",
    "penetration_total",
    "practice_source_quality",
    "ritual_casting_total",
    "score_from_xp",
    "seasonal_lab_progress",
    "simple_die",
    "spell_magnitude",
    "spontaneous_casting_total",
    "stress_die",
    "teaching_source_quality",
    "training_source_quality",
    "validate_adventure_allocations",
    "validate_non_negative_scores",
    "validate_single_xp_source",
    "validate_spell",
    "validate_spell_constraints",
    "vis_extraction",
    "vis_limit",
    "xp_to_buy_score",
    "xp_to_raise_next",
]
